version: '3.8'

services:
  frontend:
    # Development configurations for frontend service
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DEBUG=*
    # Add development tools to frontend service

  chore-service:
    # Development configurations for chore service
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DEBUG=*

  inventory-service:
    # Development configurations for inventory service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - LOG_LEVEL=DEBUG

  shopping-service:
    # Development configurations for shopping service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1

  household-service:
    # Development configurations for household service
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DEBUG=*

  # Development tools
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

volumes:
  pgadmin_data:
